### ISSUE TITLE
Failed to start Pi Radio App.

### ISSUE THREAD

**Issue by Unifolm** [trustMeIAmANinja/pi-world-radio#3]
I would like to recreate this radio. I follow the instructions, but unfortunately the app doesn't start.
in the journal it says Error: Cannot find module 'fastify', after I installed it it says Error: Cannot find module 'node-fetch'.
Was there any step forgotten in the instructions?
Thanks for the help

**Comment by trustMeIAmANinja** [comment]
Thanks for the report. I did miss a step on setting up the nodeJS dependencies. I will verify it on a clean install and update the docs.

**Comment by trustMeIAmANinja** [comment]
For now just run `npm install` inside the `app` directory which has the JS source and package.json

**Comment by Unifolm** [comment]
I tried your advice with a new installation, unfortunately the radio app still doesn't start. Maybe you have another idea. In the meantime I'm looking for a nice radio case.

**Comment by Unifolm** [comment]
it works, I tested it with a Bulleye 32 image.
It's so cool, thank you very much.

**Comment by trustMeIAmANinja** [comment]
Great. Glad it works for you.
